### ISSUE TITLE
Section 4.9

### ISSUE THREAD

**Issue by Nolapete** [Urigo/angular-meteor-docs#102]
`<Control>`does not show up in the diff text. Though it does show up if you go look at the code.  It seems that anywhere <> is used in the code the diff text is incorrect.  This is similar to the other issue I reported.

`(<Control>this.partiesForm.controls['name']).updateValue('');`
`(<Control>this.partiesForm.controls['description']).updateValue('');`
`(<Control>this.partiesForm.controls['location']).updateValue('');`

**Comment by dotansimha** [comment]
Applied a workaround in https://github.com/Urigo/angular-meteor-docs/commit/82522949a035b9fe11ae23a8a47493400d08abd2
The actual problem is that we use old version of Meteor for the website and we need to update it in order to use the new package of the diffbox that includes a fix for that.

Thanks @Nolapete 

@Urigo

**Comment by Urigo** [comment]
ok I've deployed the workaround.
Will try updating the site
