### ISSUE TITLE
using moduleId: module.id for relative paths

### ISSUE THREAD

**Issue by dohomi** [Urigo/angular-meteor-docs#145]
Hi,
I'm just digging through the docs. Would it be a benefit for the user using 

```
@Component({
    moduleId: module.id,
    selector: 'some-selector'
    (...)
})
```

It would save some writing in most of the cases. But currently I get a compile error in the console:
`Cannot find name 'module'`

**Comment by dotansimha** [comment]
You just get a TypeScript compiler warning (and the value is valid), or it's an actual runtime error?
Because Meteor implements CommonJS, and `module.id` is part of it's standard. 
Any way, yeah, it could be useful to use the `moduleId` of Angular 2 when you are not using Meteor, because Meteor already resolves the current Component's directory and fetches the files from there. it could also be useful when using assets inside the Component. 

You can read more about Angular 2 modules and it's usage [here](http://blog.thoughtram.io/angular/2016/06/08/component-relative-paths-in-angular-2.html).
